### ISSUE TITLE
Weather card as title wider than card borber.

### ISSUE THREAD

**Issue by urtaevS** [Alia5/lovelace-expander-card#1]
When choose weather card as title and it's showing "Partly cloudy" I get this:
![IMG_20230102_205546_931.jpg](https://user-images.githubusercontent.com/66906118/210265313-ebc729aa-cdeb-47b2-891a-615be056b5e1.jpg)

Maybe add multiline or else?

**Comment by urtaevS** [comment]
This on computer:
![Снимок экрана 2023-01-06 в 12 28 54](https://user-images.githubusercontent.com/66906118/210972817-973b34b8-eb62-406f-a02e-991ba3dabea4.png)

And the same card on mobile:
![Screenshot_20230106-122849445](https://user-images.githubusercontent.com/66906118/210972952-793770ce-314c-4166-9ce3-8a89b81c43c9.jpg)

**Comment by romicaiarca** [comment]
You may want to play with padding and child-padding attributes. This is my usage of the card to fix miss alignment of cards (weather cards)

```yaml
type: custom:expander-card
title-card:
  show_current: true
  show_forecast: false
  type: weather-forecast
  entity: weather.my_weather_station
  secondary_info_attribute: humidity
title-card-button-overlay: false
gap: 0em
padding: 0em
child-padding: 0em 3.6em 0em 0em
overlay-margin: 0em
cards:
  - show_current: false
    show_forecast: true
    type: weather-forecast
    entity: weather.home

```
<img width="1002" alt="Screenshot 2023-02-06 at 12 18 31" src="https://user-images.githubusercontent.com/1266110/216947064-beecb34c-592a-4d51-80d0-f447c65d5b3f.png">

<img width="987" alt="Screenshot 2023-02-06 at 12 21 01" src="https://user-images.githubusercontent.com/1266110/216947060-9f5477ec-3a31-4fc1-b990-895eb9b437ab.png">
